#RELATÓRIOS DE ATENDIMENTOS CONCLUIDOS, DIVIDIDOS POR CLASSES
#Atendimentos concluidos por unidade
SELECT U.ID_UNIDADE AS NUMERO_UNIDADE, U.DESCRICAO_UNID AS NOME,
            A.ID_AGENDAMENTO AS CODIGO_AGENDAMENTO,
            S.ID_STATUS AS CODIGO_STATUS,S.DESCRICAO_STATUS AS STATUS
               FROM UNIDADE AS U
               INNER JOIN AGENDAMENTO AS A
               ON A.ID_UNIDADE= U.ID_UNIDADE
			   INNER JOIN STATUS AS S
			   ON A.ID_STATUS= S.ID_STATUS
               WHERE S.DESCRICAO_STATUS = 'Realizado';
               
               
#Atendimentos concluido por profissional, Agrupado por nome do funcionario
SELECT F.ID_FUNCIONARIO AS CODIGO_FUNCIONARIO,F.NOME_FUNCIO AS NOME,
             A.ID_AGENDAMENTO AS AGENDAMENTOS,
             S.DESCRICAO_STATUS AS STATUS
                FROM FUNCIONARIO AS F
                INNER JOIN AGENDAMENTO AS A
                ON A.ID_FUNCIONARIO= F.ID_FUNCIONARIO
                INNER JOIN STATUS AS S
                ON A.ID_STATUS = S.ID_STATUS
                WHERE S.DESCRICAO_STATUS = 'Realizado';
                                                              
#Atendimentos concluidos por cliente
SELECT C.ID_CLIENTE AS CODIGO_CLIENTE, C.NOME_CLIENTE AS NOME,
             count(A.ID_AGENDAMENTO) AS QUANTIDADE_FREQUENCIA,
             S.DESCRICAO_STATUS AS STATUS_SERVICO
                FROM CLIENTE AS C
                INNER JOIN AGENDAMENTO AS A
                ON A.ID_CLIENTE= C.ID_CLIENTE
                INNER JOIN STATUS AS S
                ON A.ID_STATUS = S.ID_STATUS
                WHERE S.DESCRICAO_STATUS = 'Realizado'
                GROUP BY C.ID_CLIENTE;
                 


#RELAÇÃO DE FUNCIONARIOS, DIVIDIDOS POR CLASSES

#Funcionarios e sua unidade
SELECT F.ID_FUNCIONARIO AS FUNCIONARIO,F.NOME_FUNCIO AS NOME, U.ID_UNIDADE AS UNIDADE, U.DESCRICAO_UNID AS NOME_UNIDADE
FROM UNIDADE AS U
INNER JOIN FUNCIONARIO AS F
  ON  F.ID_UNIDADE= U.ID_UNIDADE;
   
  
#Funcionarios e sua agenda
SELECT F.ID_FUNCIONARIO AS CODIGO_FUNCIONARIO, F.NOME_FUNCIO AS FUNCIONARIO,
           A.ID_AGENDAMENTO AS AGENDAMENTO, A.DATA_AGEN AS DATA, A.HORARIO_INICIAL AS INICIO, A.HORARIO_FINAL AS FINAL
           FROM AGENDAMENTO AS A
           INNER JOIN FUNCIONARIO AS F
           ON A.ID_FUNCIONARIO=F.ID_FUNCIONARIO
           ORDER BY A.DATA_AGEN ASC,
					A.HORARIO_INICIAL ASC;
 

 
 
#RELATÓRIOS DE SITUAÇÃO DE AGENDAMENTOS
  
 #Relatório de agendamentos do dia
 SELECT U.ID_UNIDADE AS UNIDADE, A.ID_AGENDAMENTO AS AGENDAMENTO,
        A.DATA_AGEN AS DATA, C.ID_CLIENTE AS CLIENTE 
        FROM UNIDADE AS U 
        INNER JOIN AGENDAMENTO AS A 
        ON U.ID_UNIDADE = A.ID_UNIDADE 
        INNER JOIN CLIENTE AS C 
        ON C.ID_CLIENTE= A.ID_CLIENTE 
        WHERE A.DATA_AGEN = now() ;
        
#Relação de um agendamentos que estejam em lista de espera
SELECT A.FILA_ESPERA AS ESPERA,
	   A.ID_AGENDAMENTO AGENDAMENTO
       FROM AGENDAMENTO AS A
		WHERE FILA_ESPERA = 1;
        
#Agendamentos cancelados
SELECT A.ID_AGENDAMENTO AS AGENDAMENTO,
	   D.ID_STATUS AS CODIGO,D.DESCRICAO_STATUS AS STATUS
	   FROM AGENDAMENTO AS A
		INNER JOIN STATUS AS D
		ON D.ID_STATUS=A.ID_STATUS
		WHERE D.DESCRICAO_STATUS='cancelado';

#RELATÓRIO REFERENTE A PROMOÇÃO

#Quantidade de agendamentos participantes da promoção, agrupados por unidade
SELECT COUNT(A.PROMOCAO) AS QUANTIDADE_PROMOCAO,
U.DESCRICAO_UNID AS NOME,
U.ID_UNIDADE AS UNIDADE
       
       FROM AGENDAMENTO AS A
       INNER JOIN UNIDADE AS U
	   ON A.ID_UNIDADE= U.ID_UNIDADE
       GROUP BY U.ID_UNIDADE;
      
       
       
#RANKINGS 

#Ranking de agendamentos concluidos por funcionarios
SELECT F.ID_FUNCIONARIO AS FUNCIONARIO, F.NOME_FUNCIO AS NOME,
       COUNT(A.ID_AGENDAMENTO) AS QUANTIDADE
       FROM FUNCIONARIO AS F
       INNER JOIN AGENDAMENTO AS A
       ON A.ID_FUNCIONARIO= F.ID_FUNCIONARIO
       GROUP BY F.ID_FUNCIONARIO
       ORDER BY QUANTIDADE DESC;
       
#Ranking de unidades que mais possuem agendamentos concluidos
SELECT U.ID_UNIDADE AS NUMERO_UNIDADE, U.DESCRICAO_UNID AS NOME,
            COUNT(A.ID_AGENDAMENTO) AS QUANTIDADE,
            S.ID_STATUS AS CODIGO_STATUS,S.DESCRICAO_STATUS AS STATUS
               FROM UNIDADE AS U
               INNER JOIN AGENDAMENTO AS A
               ON A.ID_UNIDADE= U.ID_UNIDADE
			   INNER JOIN STATUS AS S
			   ON A.ID_STATUS= S.ID_STATUS
               WHERE S.DESCRICAO_STATUS = 'Realizado'
               GROUP BY U.ID_UNIDADE
               ORDER BY QUANTIDADE DESC;